
services:
  flaskapp:
    build: .
    container_name: MegaSIP
    ports:
      - "5008:5008"
    volumes:
      - .:/app
      - /mnt/base_ventas/Asistente Ventas:/mnt/excel
    environment:
      - FLASK_ENV=production